# Generated by Django 5.1.4 on 2024-12-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за час')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
        ),
    ]
